name: flutter_app
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  cupertino_icons: ^1.0.2
  location: ^4.3.0
  geocoding: ^2.0.2
  http: ^0.13.4
  intl: ^0.17.0
  flutter_svg: ^0.22.0
  google_fonts: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Roboto Slab
      fonts: 
        - asset: assets/fonts/robotoslablight300.ttf
          weight: 300
        - asset: assets/fonts/robotoslabmedium500.ttf
          weight: 500